[project]
name = 'racing-game-betting-smart'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stx-racing-game-betting-smart]
path = 'contracts/stx-racing-game-betting-smart.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
